sudo: required

git:
  depth: false

language: python

python: '3.5'

services:
- docker
env:
  global:
    secure: q+XAO2nUC2TGVgmjhS7g2y3TclLGgZN9M2qbgtkzvOlb+WAnkcKl40na9uEtQL7zMqsM6yFl77Kto723B5kLZ3rActOt9k9B+4eEhxfnpupxuqB5JqR81kA+zOPDz9kvV1nQj5J7BW3ukmOg47OIIrxMuhPLw+VKm/EJHIjdU7KnwvZnWWPAMTAoC3gFhGLBETa4A29QRUeP6JM8dZSnV9jZthPL3AaoqTOtHij386oS0mhAFe+5AicwwU8EU8im+GBvS/WlZsi70IQrOEpLUVZyX23dLgzH5A2+JsZKEyl+v0be1bzNVJe+GooW9QY11tTQXqTy0EiFdH2H1YX6pgLSruN5nQrRj/ZTKeNfwm44AJufBFr7jcSQ1cIwzUgGCJLAc87D7rIm15J48oZCkMHerzdZmRrZ2lmL2SC0BVbFfm1n8Xr2K8DyO64LdtTzVPtC8jH6WEKLezzRN6s3nLuFOwamW/RQX/MrcdNdrwAUtf0vIGxw/Sg71Zmauj45H3qE+b/NeWRWeIy3Ln7Z9eW7f1kfhCYziQbHN8r0CIEQq9E9WmhWbyg4XRmAMqqm9dvSJvKyzRIGijJSadmkboDrirLKU6z8sw5hDVWCENXqyCQqiHxSnZ6u+qXzqiCrhA6aPy0w1GcL3+At2dSxcYQ1PEgwR6Gqg09Ea4g+3LU=

before_script:
  - pip install seaworthy==0.2.1.2
  - chmod +x ./ci/build.sh

script:
  - ./ci/build.sh -i "${HTTPD_IMAGE_NAME}" -t "${TRAVIS_TAG}" -b "${TRAVIS_BRANCH}" -T "${HTTPD_WAIT_TIMEOUT}" -e "${TRAVIS_EVENT_TYPE}"

after_script:
  - docker images

before_deploy:
  - echo "${DOCKER_HUB_PASS}" | docker login -u "${DOCKER_HUB_USER}" --password-stdin
  - pip install docker-ci-deploy==0.3.0
  - pip install semantic_version==2.6.0
  - chmod +x ./ci/deploy.sh

deploy:
  provider: script
  script: ./ci/deploy.sh -i "${HTTPD_IMAGE_NAME}" -t "${TRAVIS_TAG}" -b "${TRAVIS_BRANCH}"
  on:
    all_branches: true

branches:
  only:
    - /^\d+\.\d+(-dev)?$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/